# Use an official Ubuntu as a parent image
FROM ubuntu:latest

# Install Apache HTTP server
RUN apt-get update && apt-get install -y apache2 tcpdump tshark net-tools

# Expose port 80
EXPOSE 80

# Start Apache in the foreground
CMD ["apachectl", "-D", "FOREGROUND"]